# Use an official Python runtime as a parent image
FROM python:3.12

# Install system dependencies required for potential Python packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

# Copying code from current directory to container's code directory
COPY . /code/

# Configuration to avoid creating virtual environments inside the Docker container
RUN poetry config virtualenv.create false

RUN poetry install

EXPOSE 8080

# Run the app. CMD can be overridden when starting the container
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]